In [58]:
import numpy as np
import pandas as pd

In [59]:
df1 = pd.read_csv('ADNI_Training_Q3_APOE_CollectionADNI1Complete 1Yr 1.5T_July22.2014.csv')
df1.head()

,directory.id,Subject,RID,Image.Data.ID,Modality,Visit,Acq.Date,DX.bl,EXAMDATE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,APOE4,MMSE,imputed_genotype,APOE Genotype,Dx Codes for Submission
0,4702245ea294ce5d4e9b8a87027dfdf4,011_S_0003,3,32237,MRI,1,9/1/05,AD,9/12/05,81.3,Male,18,Not Hisp/Latino,White,1,20,True,"3,4",AD
1,2e89e352af743597b2368c412e0f6de2,022_S_0004,4,64631,MRI,1,9/22/05,LMCI,11/8/05,67.5,Male,10,Hisp/Latino,White,0,27,False,"3,3",MCI
2,90419199306997753de8042f1fd55e38,011_S_0005,5,32246,MRI,1,9/2/05,CN,9/7/05,73.7,Male,16,Not Hisp/Latino,White,0,29,True,"3,3",CN
3,d8d175ffff1e2053e6a18c5df494ccdf,100_S_0006,6,33025,MRI,1,11/15/05,LMCI,11/29/05,80.4,Female,13,Not Hisp/Latino,White,0,25,True,"3,3",MCI
4,986e75b2e604cd44b38feb2188476fb2,011_S_0010,10,32270,MRI,1,11/7/05,AD,11/10/05,73.9,Female,12,Not Hisp/Latino,White,1,24,True,"3,4",AD

In [60]:
df1['PTGENDER'] = df1['PTGENDER'].replace({'Male': 1, 'Female': 0})

df1['DX.bl'] = df1['DX.bl'].replace({"CN": 0, "LMCI": 0.5, "AD": 1})

/tmp/ipykernel_189/973893439.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['PTGENDER'] = df1['PTGENDER'].replace({'Male': 1, 'Female': 0})
/tmp/ipykernel_189/973893439.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['DX.bl'] = df1['DX.bl'].replace({"CN": 0, "LMCI": 0.5, "AD": 1})

In [61]:
df2 = pd.read_excel('oasis_cross-sectional-5708aa0a98d82080.xlsx')
df2.head()

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344,0.743,1.306,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147,0.810,1.531,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454,0.708,1.207,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588,0.803,1.105,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737,0.848,1.010,NaN

In [62]:
df2["M/F"] = df2["M/F"].replace({'M': 1, 'F': 0})

/tmp/ipykernel_189/3304890419.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2["M/F"] = df2["M/F"].replace({'M': 1, 'F': 0})

In [63]:
df3 = pd.read_excel('oasis_longitudinal_demographics-8d83e569fa2e2d30.xlsx')
df3.head()

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,OAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2.0,27.0,0.0,1986.550000,0.696106,0.883440
1,OAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2.0,30.0,0.0,2004.479526,0.681062,0.875539
2,OAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,NaN,23.0,0.5,1678.290000,0.736336,1.045710
3,OAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,NaN,28.0,0.5,1737.620000,0.713402,1.010000
4,OAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,NaN,22.0,0.5,1697.911134,0.701236,1.033623

In [64]:
df3["M/F"] = df3["M/F"].replace({'M': 1, 'F': 0})

/tmp/ipykernel_189/1801427457.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3["M/F"] = df3["M/F"].replace({'M': 1, 'F': 0})

In [65]:
df1 = df1[["Subject","AGE","PTGENDER","PTEDUCAT","MMSE","DX.bl"]]

df2 = df2[["ID","Age","M/F","Educ","MMSE","eTIV","nWBV","CDR"]]

df3 = df3[["Subject ID","Age","M/F","EDUC","MMSE","eTIV","nWBV","CDR"]]

In [66]:
df1.columns = ["ID","Age","Gender","Educ","MMSE","Diagnosis"]

df2.columns = ["ID","Age","Gender","Educ","MMSE","eTIV","nWBV","CDR"]

df3.columns = ["ID","Age","Gender","Educ","MMSE","eTIV","nWBV","CDR"]

In [67]:
df4 = pd.concat([df1, df2, df3], ignore_index=True)

In [68]:
df4

,ID,Age,Gender,Educ,MMSE,Diagnosis,eTIV,nWBV,CDR
0,011_S_0003,81.3,1,18.0,20.0,1.0,NaN,NaN,NaN
1,022_S_0004,67.5,1,10.0,27.0,0.5,NaN,NaN,NaN
2,011_S_0005,73.7,1,16.0,29.0,0.0,NaN,NaN,NaN
3,100_S_0006,80.4,0,13.0,25.0,0.5,NaN,NaN,NaN
4,011_S_0010,73.9,0,12.0,24.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1432,OAS2_0185,82.0,1,16.0,28.0,NaN,1692.880000,0.693926,0.5
1433,OAS2_0185,86.0,1,16.0,26.0,NaN,1688.009649,0.675457,0.5
1434,OAS2_0186,61.0,0,13.0,30.0,NaN,1319.020000,0.801006,0.0
1435,OAS2_0186,63.0,0,13.0,30.0,NaN,1326.650000,0.795981,0.0
1436,OAS2_0186,65.0,0,13.0,30.0,NaN,1332.944463,0.801248,0.0

In [69]:

df4 = df4.replace({np.nan: ''})
df4

,ID,Age,Gender,Educ,MMSE,Diagnosis,eTIV,nWBV,CDR
0,011_S_0003,81.3,1,18.0,20.0,1.0,,,
1,022_S_0004,67.5,1,10.0,27.0,0.5,,,
2,011_S_0005,73.7,1,16.0,29.0,0.0,,,
3,100_S_0006,80.4,0,13.0,25.0,0.5,,,
4,011_S_0010,73.9,0,12.0,24.0,1.0,,,
...,...,...,...,...,...,...,...,...,...
1432,OAS2_0185,82.0,1,16.0,28.0,,1692.88,0.693926,0.5
1433,OAS2_0185,86.0,1,16.0,26.0,,1688.009649,0.675457,0.5
1434,OAS2_0186,61.0,0,13.0,30.0,,1319.02,0.801006,0.0
1435,OAS2_0186,63.0,0,13.0,30.0,,1326.65,0.795981,0.0
1436,OAS2_0186,65.0,0,13.0,30.0,,1332.944463,0.801248,0.0

In [70]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1437 entries, 0 to 1436
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1437 non-null   object
 1   Age        1437 non-null   float64
 2   Gender     1437 non-null   int64
 3   Educ       1437 non-null   object
 4   MMSE       1437 non-null   object
 5   Diagnosis  1437 non-null   object
 6   eTIV       1437 non-null   object
 7   nWBV       1437 non-null   object
 8   CDR        1437 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 101.2+ KB