### Import Modules

In [1]:
import numpy as np
import pandas as pd

### Load Datasets From 3 Sources

In [2]:
df1 = pd.read_csv('data/csv/ADNI_Training_Q3_APOE_CollectionADNI1Complete 1Yr 1.5T_July22.2014.csv')
df1.head()

,directory.id,Subject,RID,Image.Data.ID,Modality,Visit,Acq.Date,DX.bl,EXAMDATE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,APOE4,MMSE,imputed_genotype,APOE Genotype,Dx Codes for Submission
0,4702245ea294ce5d4e9b8a87027dfdf4,011_S_0003,3,32237,MRI,1,9/1/05,AD,9/12/05,81.3,Male,18,Not Hisp/Latino,White,1,20,True,"3,4",AD
1,2e89e352af743597b2368c412e0f6de2,022_S_0004,4,64631,MRI,1,9/22/05,LMCI,11/8/05,67.5,Male,10,Hisp/Latino,White,0,27,False,"3,3",MCI
2,90419199306997753de8042f1fd55e38,011_S_0005,5,32246,MRI,1,9/2/05,CN,9/7/05,73.7,Male,16,Not Hisp/Latino,White,0,29,True,"3,3",CN
3,d8d175ffff1e2053e6a18c5df494ccdf,100_S_0006,6,33025,MRI,1,11/15/05,LMCI,11/29/05,80.4,Female,13,Not Hisp/Latino,White,0,25,True,"3,3",MCI
4,986e75b2e604cd44b38feb2188476fb2,011_S_0010,10,32270,MRI,1,11/7/05,AD,11/10/05,73.9,Female,12,Not Hisp/Latino,White,1,24,True,"3,4",AD

In [3]:
df2 = pd.read_excel('data/csv/oasis_cross-sectional-5708aa0a98d82080.xlsx')
df2.head()

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344,0.743,1.306,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147,0.810,1.531,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454,0.708,1.207,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588,0.803,1.105,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737,0.848,1.010,NaN

In [4]:
df3 = pd.read_excel('data/csv/oasis_longitudinal_demographics-8d83e569fa2e2d30.xlsx')
df3.head()

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,OAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2.0,27.0,0.0,1986.550000,0.696106,0.883440
1,OAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2.0,30.0,0.0,2004.479526,0.681062,0.875539
2,OAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,NaN,23.0,0.5,1678.290000,0.736336,1.045710
3,OAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,NaN,28.0,0.5,1737.620000,0.713402,1.010000
4,OAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,NaN,22.0,0.5,1697.911134,0.701236,1.033623

In [5]:
kaggle = pd.read_csv('data/csv/alzheimers_disease_data.csv')
kaggle.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,4751,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,4752,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,4753,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,4754,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,4755,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid

### Data Harmoinzation

In [7]:
kaggle.columns

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality',
       'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease',
       'Diabetes', 'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP',
       'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment',
       'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion',
       'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks',
       'Forgetfulness', 'Diagnosis', 'DoctorInCharge'],
      dtype='object')

In [20]:
kaggle['EducationLevel'].value_counts()

EducationLevel
1    854
2    636
0    446
3    213
Name: count, dtype: int64

In [9]:
df1['PTGENDER'] = df1['PTGENDER'].replace({'Male': 1, 'Female': 0})

df1['DX.bl'] = df1['DX.bl'].replace({"CN": 0, "LMCI": 0.5, "AD": 1})

C:\Users\zyado\AppData\Local\Temp\ipykernel_26496\973893439.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['PTGENDER'] = df1['PTGENDER'].replace({'Male': 1, 'Female': 0})
C:\Users\zyado\AppData\Local\Temp\ipykernel_26496\973893439.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['DX.bl'] = df1['DX.bl'].replace({"CN": 0, "LMCI": 0.5, "AD": 1})

In [10]:
df2["M/F"] = df2["M/F"].replace({'M': 1, 'F': 0})

C:\Users\zyado\AppData\Local\Temp\ipykernel_26496\3304890419.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2["M/F"] = df2["M/F"].replace({'M': 1, 'F': 0})

In [11]:
df3["M/F"] = df3["M/F"].replace({'M': 1, 'F': 0})

C:\Users\zyado\AppData\Local\Temp\ipykernel_26496\3451063201.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3["M/F"] = df3["M/F"].replace({'M': 1, 'F': 0})

### Check After Harmonization

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628 entries, 0 to 627
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   directory.id             628 non-null    object
 1   Subject                  628 non-null    object
 2   RID                      628 non-null    int64
 3   Image.Data.ID            628 non-null    int64
 4   Modality                 628 non-null    object
 5   Visit                    628 non-null    int64
 6   Acq.Date                 628 non-null    object
 7   DX.bl                    628 non-null    float64
 8   EXAMDATE                 628 non-null    object
 9   AGE                      628 non-null    float64
 10  PTGENDER                 628 non-null    int64
 11  PTEDUCAT                 628 non-null    int64
 12  PTETHCAT                 628 non-null    object
 13  PTRACCAT                 628 non-null    object
 14  APOE4                    628 non-null    int64
 15  MMSE                     628 non-null    int64
 16  imputed_genotype         627 non-null    object
 17  APOE Genotype            628 non-null    object
 18  Dx Codes for Submission  628 non-null    object
dtypes: float64(2), int64(7), object(10)
memory usage: 93.3+ KB

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      436 non-null    object
 1   M/F     436 non-null    int64
 2   Hand    436 non-null    object
 3   Age     436 non-null    int64
 4   Educ    235 non-null    float64
 5   SES     216 non-null    float64
 6   MMSE    235 non-null    float64
 7   CDR     235 non-null    float64
 8   eTIV    436 non-null    int64
 9   nWBV    436 non-null    float64
 10  ASF     436 non-null    float64
 11  Delay   20 non-null     float64
dtypes: float64(7), int64(3), object(2)
memory usage: 41.0+ KB

In [14]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Subject ID  373 non-null    object
 1   MRI ID      373 non-null    object
 2   Group       373 non-null    object
 3   Visit       373 non-null    int64
 4   MR Delay    373 non-null    int64
 5   M/F         373 non-null    int64
 6   Hand        373 non-null    object
 7   Age         373 non-null    int64
 8   EDUC        373 non-null    int64
 9   SES         354 non-null    float64
 10  MMSE        371 non-null    float64
 11  CDR         373 non-null    float64
 12  eTIV        373 non-null    float64
 13  nWBV        373 non-null    float64
 14  ASF         373 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 43.8+ KB

In [15]:
kaggle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       2149 non-null   int64
 1   Age             2149 non-null   int64
 2   Gender          2149 non-null   int64
 3   EducationLevel  2149 non-null   int64
 4   MMSE            2149 non-null   float64
 5   Diagnosis       2149 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 100.9 KB

### Drop Unimportant Coulmns & Change Columns Name

In [22]:
df1 = df1[["Subject","AGE","PTGENDER","PTEDUCAT","MMSE","DX.bl"]]

df2 = df2[["ID","Age","M/F","Educ","MMSE","eTIV","nWBV","CDR"]]

df3 = df3[["Subject ID","Age","M/F","EDUC","MMSE","eTIV","nWBV","CDR"]]

kaggle = kaggle[['PatientID', 'Age', 'Gender', 'EducationLevel', 'MMSE', 'Diagnosis']]

In [23]:
df1.columns = ["ID","Age","Gender","Educ","MMSE","Target"]

df2.columns = ["ID","Age","Gender","Educ","MMSE","eTIV","nWBV","Target"]

df3.columns = ["ID","Age","Gender","Educ","MMSE","eTIV","nWBV","Target"]

kaggle.columns = ["ID","Age","Gender","Educ","MMSE","Target"]

### Merging All Datasets

In [24]:
df4 = pd.concat([df1, df2, df3, kaggle], ignore_index=True)
df4.head()

           ID   Age  Gender  Educ  MMSE  Target  eTIV  nWBV
0  011_S_0003  81.3       1  18.0  20.0     1.0   NaN   NaN
1  022_S_0004  67.5       1  10.0  27.0     0.5   NaN   NaN
2  011_S_0005  73.7       1  16.0  29.0     0.0   NaN   NaN
3  100_S_0006  80.4       0  13.0  25.0     0.5   NaN   NaN
4  011_S_0010  73.9       0  12.0  24.0     1.0   NaN   NaN

In [25]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3586 entries, 0 to 3585
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      3586 non-null   object
 1   Age     3586 non-null   float64
 2   Gender  3586 non-null   int64
 3   Educ    3385 non-null   float64
 4   MMSE    3383 non-null   float64
 5   Target  3385 non-null   float64
 6   eTIV    809 non-null    float64
 7   nWBV    809 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 224.3+ KB

### Handling The Merged Dataset

In [30]:
df4.value_counts('Target')

Target
0.0    1920
1.0    1465
Name: count, dtype: int64

In [29]:
df4['Target'] = df4['Target'].replace({0: 0, 0.5: 1, 1: 1, 2: 1})

In [31]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df4[['eTIV', 'nWBV']] = imputer.fit_transform(df4[['eTIV', 'nWBV']])
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3586 entries, 0 to 3585
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      3586 non-null   object
 1   Age     3586 non-null   float64
 2   Gender  3586 non-null   int64
 3   Educ    3385 non-null   float64
 4   MMSE    3383 non-null   float64
 5   Target  3385 non-null   float64
 6   eTIV    3586 non-null   float64
 7   nWBV    3586 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 224.3+ KB

In [32]:
df4.dropna(subset=['Target'], inplace=True)
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3385 entries, 0 to 3585
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      3385 non-null   object
 1   Age     3385 non-null   float64
 2   Gender  3385 non-null   int64
 3   Educ    3385 non-null   float64
 4   MMSE    3383 non-null   float64
 5   Target  3385 non-null   float64
 6   eTIV    3385 non-null   float64
 7   nWBV    3385 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 238.0+ KB

###  Standardization The Dataset

In [34]:
def harmonize_education(value):
    if pd.isna(value): return np.nan
    if isinstance(value, (int, float)):
        if value > 6: # Years of Education (e.g., 16 years)
            if value < 12: return 0
            if value == 12: return 1
            if 13 <= value <= 15: return 2
            if value == 16: return 3
            if value > 16: return 4
        elif 1 <= value <= 5: # OASIS-1 Scale (1-5)
            return int(value - 1)
        elif 0 <= value <= 4: # Already standardized
            return int(value)
    return np.nan

In [35]:
df4['Educ'] = df4['Educ'].apply(harmonize_education)
df4['Educ'].value_counts()

Educ
0.0    1378
1.0     886
2.0     459
4.0     370
3.0     287
Name: count, dtype: int64

In [38]:
df4.dropna(subset=['MMSE'], inplace=True)
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3378 entries, 0 to 3585
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      3378 non-null   object
 1   Age     3378 non-null   float64
 2   Gender  3378 non-null   int64
 3   Educ    3378 non-null   float64
 4   MMSE    3378 non-null   float64
 5   Target  3378 non-null   float64
 6   eTIV    3378 non-null   float64
 7   nWBV    3378 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 237.5+ KB

In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
continuous_cols = ['Age', 'MMSE', 'eTIV', 'nWBV']
df4[continuous_cols] = scaler.fit_transform(df4[continuous_cols])

In [40]:
df4.describe()

,Age,Gender,Educ,MMSE,Target,eTIV,nWBV
count,3.378000e+03,3378.000000,3378.000000,3.378000e+03,3378.000000,3.378000e+03,3.378000e+03
mean,8.539975e-16,0.499112,1.226465,-1.346203e-16,0.431616,6.069482e-15,5.317502e-15
std,1.000148e+00,0.500073,1.348592,1.000148e+00,0.495375,1.000148e+00,1.000148e+00
min,-4.783867e+00,0.000000,0.000000,-2.074129e+00,0.000000,-5.263635e+00,-5.551157e+00
25%,-6.921079e-01,0.000000,0.000000,-8.732590e-01,0.000000,1.474271e-02,2.237236e-01
50%,-1.820738e-04,0.000000,1.000000,2.973972e-01,0.000000,1.474271e-02,2.237236e-01
75%,7.970987e-01,1.000000,2.000000,9.251540e-01,1.000000,1.474271e-02,2.237236e-01
max,2.619455e+00,1.000000,4.000000,1.159978e+00,1.000000,7.250253e+00,4.297528e+00

### Save The Final Dataset

In [41]:
df4.to_csv('data/csv/Alzheimer_final.csv', index=False)